name: Generate V1-Only Permissions Data
description: Converts RBAC config permissions JSON to a KSIL file representing permissions declared in V1 but not yet migrated to the V2 model
runs:
  using: docker
  image: Dockerfile
  args:
    - "-ksl"
    - ${{ inputs.ksl }}
    - "-rbac-permissions-json"
    - ${{ inputs.rbac_permissions }}
inputs:
  ksl:
    description: Path to the KSL project directory for the job
    required: true
  rbac_permissions:
    description: Path to the RBAC permissions directory for the job
    required: true